FROM maven:3.8.5-openjdk-17 AS build 
COPY . . 
RUN mvn clean package -DskipTests

FROM openjdk:17.0.1-jdk-slim
COPY --from=build /target/Main-0.0.1-SNAPSHOT.jar Main.jar
EXPOSE 8080
ENTRYPOINT ["Java" , "-jar", "Main.jar"]